### ISSUE TITLE
Fix up unmaintained canvases

### ISSUE THREAD

**Issue by BrickGrass** [BrickGrass/StarlightGlimmer#12]
~~I'm not maintaining them, so they're probably all sorts of broken by now, and removing a couple would mean that I can remove some dependencies. Ofc I'm going to think it over a *bit* more, cause breaking change and all that.~~

Todos:

- [x] pixelzone template alerts
- [x] pixelzone g!d -e
- [x] pixelzone g!dither
- [x] pxlsspace template alerts
- [x] pxlsspace g!d -e
- [x] pxlsspace g!dither

I should centralise my canvas websocket listeners into one place (it's own file inside utils or ext/template/alerts? maybe inside utils, but they get booted and shut off inside the alert cog? I'll see). Oh and I should do what I've already done with g!d -e error trackers for template alerts, superclass that handles formatting with subclasses that handle the implementation of getting the pixel data.

**Comment by BrickGrass** [comment]
Actually, changed my mind, lets get all the other canvases working again, might be fun!

**Comment by DiamondIceNS** [comment]
If you would like some pointers on the other canvas formats (particularly Pixelzone) to help get you started, you can DM me on Discord.

**Comment by BrickGrass** [comment]
Thanks dude, will do.

**Comment by BrickGrass** [comment]
All features work for all canvases again 🎊
