### ISSUE TITLE
Add delay between pxls.space/ws requests

### ISSUE THREAD

**Issue by VanillaSixtySix** [BrickGrass/StarlightGlimmer#18]
I noticed this script making ~16 requests per second to the `pxls.space/ws` endpoint when it responds with 502, flooding the access log.

**Comment by BrickGrass** [comment]
https://github.com/BrickGrass/StarlightGlimmer/blob/c08607148d919ac33c711b94e9674dc86b1e06ac/utils/websocket.py#L381 the code starting right here should exponentially rate limit on failures, is that not working whatsoever or is it not increasing it's timeouts fast enough?

**Comment by VanillaSixtySix** [comment]
> https://github.com/BrickGrass/StarlightGlimmer/blob/c08607148d919ac33c711b94e9674dc86b1e06ac/utils/websocket.py#L381
> 
> the code starting right here should exponentially rate limit on failures, is that not working whatsoever or is it not increasing it's timeouts fast enough?

Someone might be running a fork of the bot without any sort of rate limiting, so if this was already a feature, my bad!

**Comment by BrickGrass** [comment]
Well my code could still be faulty! If you're in contact with the person running this instance double check what code they're running at that section, and if it is mine I can totally take a look :)
