### ISSUE TITLE
[Feature Request] Add a Guide to Basic Usage of Glimmer 

### ISSUE THREAD

**Issue by RickeyJLancaster** [BrickGrass/StarlightGlimmer#5]
Example of the command response: ![image](https://user-images.githubusercontent.com/58918933/76703246-91289800-668d-11ea-9a69-9e0755ff92b0.png)

**Comment by BrickGrass** [comment]
Mmmh, like a quickstart or cheatsheet command?

**Comment by RickeyJLancaster** [comment]
ye something like that, with the main commands
